const stripe = require("stripe")(
  "sk_test_99G2nExhaGlqmIPbunQMl1h8"
);

// module.exports = {
// friendlyName: 'post-payment',

// description: 'Creates a charge after receiving token from Stripe Checkout API',

// extendedDescription: 'This function first checks if there is a stripe customer associated with the current customer.' +
//   'If there is not, a customer will be created in the system.',

// inputs: {

//   token: {
//     type: 'string',
//     description: 'Token generated by the Stripe checkout api'
//   }
// },

// exits: {

//   success: {
//     statusCode: 200
//   },

//   error: {
//     error: 'an unknown error occurred'
//   }
// },
// postPayment: async function (inputs, exits) {
//   await console.log(inputs.stripeToken)
//   const charge = await stripe.charges.create({
//     amount: 9.99,
//     currency: "usd",
//     description: 'Event scheduling notifications',
//     source: inputs.stripeToken.id,
//   });

//   if (charge) exits.success(charge)
//   else exits.error()
// }
// }

  const fn = async function (req, res) {
    const token = req.body;
    console.log(token)
    const id = token.id
    const charge = await stripe.charges.create({
      amount: 100,
      currency: "usd",
      description: 'Event scheduling notifications',
      source: id,
    });
    const userToUpdate = CryptographyService.decrypt(req.cookies.user)
    if (charge.paid) {
      User.update({ id: userToUpdate })
      .set({ isAdmin: true })
      res.json(charge)
    }
    else if (err) console.log(err)
  }

  module.exports = fn
// }
