// const Stripe = require('machinepack-stripe')('pk_test_K02516PB2chdseApGKRYxHbZ')
// module.exports = {
//   friendlyName: 'postPayment',
//   description: 'Creates a charge after receiving token from Stripe Checkout API',
//   extendedDescription: 'This function first checks if there is a stripe customer associated with the current customer.' +
//     'If there is not, a customer will be created in the system.',
//   inputs: {
//     emailAddress: {
//       type: string,
//       descrition: 'customer\'s email address'
//     },
//     token: {
//       type: string,
//       description: 'Token generated by the Stripe checkout api'
//     }
//   },
//   exits: {
//     success: {
//       statusCode: 200
//     },
//     error: {
//       error: 'an unknown error occurred'
//     }
//   },


//   fn: async function (inputs, exits) {
     
//   }

//   }
// }
